// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AssignmentsController from "./assignments_controller"
application.register("assignments", AssignmentsController)

import FetchAssignmentsController from "./fetch_assignments_controller"
application.register("fetch-assignments", FetchAssignmentsController)

import SortDashboardController from "./sort_dashboard_controller"
application.register("sort-dashboard", SortDashboardController)
